# Generated by Django 5.2.7 on 2025-11-04 05:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_default_styles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='styletemplate',
            name='favorite_users',
            field=models.ManyToManyField(blank=True, related_name='favorite_style_templates', to=settings.AUTH_USER_MODEL),
        ),
    ]
