# Generated by Django 5.2.7 on 2025-11-04 16:43

from django.db import migrations, models


def forwards(apps, schema_editor):
    ChatSession = apps.get_model('chat', 'ChatSession')
    mapping = {
        'deepseek-chat': 'trustai-chat',
        'deepseek-coder': 'trustai-coder',
        'deepseek-reasoner': 'trustai-reasoner',
    }
    for old, new in mapping.items():
        ChatSession.objects.filter(model_choice=old).update(model_choice=new)


def backwards(apps, schema_editor):
    ChatSession = apps.get_model('chat', 'ChatSession')
    mapping = {
        'trustai-chat': 'deepseek-chat',
        'trustai-coder': 'deepseek-coder',
        'trustai-reasoner': 'deepseek-reasoner',
    }
    for old, new in mapping.items():
        ChatSession.objects.filter(model_choice=old).update(model_choice=new)


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_styletemplate_favorite_users'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name='chatsession',
            name='model_choice',
            field=models.CharField(choices=[('trustai-chat', 'TrustAI Chat'), ('trustai-coder', 'TrustAI Coder'), ('trustai-reasoner', 'TrustAI Reasoner')], default='trustai-chat', max_length=32),
        ),
    ]
