# Generated by Django 5.2.7 on 2025-11-04 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatsession_model_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleTemplateReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, 'Me gusta'), (-1, 'No me gusta')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_reactions', to='chat.styletemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_style_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reacción de estilo',
                'verbose_name_plural': 'reacciones de estilo',
                'unique_together': {('style', 'user')},
            },
        ),
        migrations.AddField(
            model_name='styletemplate',
            name='reactions',
            field=models.ManyToManyField(blank=True, related_name='style_template_reactions', through='chat.StyleTemplateReaction', to=settings.AUTH_USER_MODEL),
        ),
    ]
