# Generated by Django 5.2.7 on 2025-11-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subscriptioncode_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deepseek_api_key',
            field=models.CharField(blank=True, help_text='Clave privada usada para conectar tus chats directamente con DeepSeek.', max_length=255, verbose_name='DeepSeek API key'),
        ),
    ]
