# Generated by Django 5.2.7 on 2025-11-04 19:46

import django.db.models.deletion
import downloads.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=downloads.models.resource_image_upload_to)),
                ('file', models.FileField(upload_to=downloads.models.resource_upload_to)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'recurso descargable',
                'verbose_name_plural': 'recursos descargables',
                'ordering': ('-created_at',),
            },
        ),
    ]
